ALTER TABLE TAIKHOAN ADD VAITRO INT;
--0 QLCH
--1 NVCH
--2 NVHT
UPDATE TAIKHOAN 
SET VAITRO = 1
WHERE manv IN (SELECT MANV
                FROM NHANVIEN
                WHERE MADV LIKE 'CH%');

UPDATE TAIKHOAN 
SET VAITRO = 0
WHERE manv IN ('NV01', 'NV06', 'NV11', 'NV16');

UPDATE TAIKHOAN 
SET VAITRO = 2
WHERE manv IN (SELECT MANV
                FROM NHANVIEN
                WHERE MADV NOT LIKE 'CH%');