--Rang buoc mien gia tri
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_gtinh_nv CHECK (GIOITINH IN ('Nam', 'Nu'));
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_gtinh_kh CHECK (GIOITINH IN ('Nam', 'Nu'));
ALTER TABLE SANPHAM ADD CONSTRAINT chk_dvt CHECK (DVT IN ('chiec', 'cai', 'bo', 'cap', 'doi'));

--Khoa ngoai
--TAIKHOAN
ALTER TABLE TAIKHOAN ADD CONSTRAINT fk_tk_nv FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);
--CUAHANG
ALTER TABLE CUAHANG ADD CONSTRAINT fk_ch_nv FOREIGN KEY (MA_NGQL) REFERENCES NHANVIEN(MANV);

--PHONGBAN 
ALTER TABLE PHONGBAN ADD CONSTRAINT fk_pb_nv FOREIGN KEY (MA_TRGPB) REFERENCES NHANVIEN(MANV);

--KHO
ALTER TABLE KHO ADD CONSTRAINT fk_kho_nv FOREIGN KEY (MA_NGQL) REFERENCES NHANVIEN(MANV);

--CTTON
ALTER TABLE CTTON ADD CONSTRAINT fk_ctton_sp FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);

--CTHD
ALTER TABLE CTHD ADD CONSTRAINT fk_cthd_hd FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD);

--HOADON
ALTER TABLE HOADON ADD CONSTRAINT fk_hd_km FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM);