/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
/**
 *
 * @author DOAN TU QUYNH
 */
public class DoanhThu extends javax.swing.JFrame {

    /**
     * Creates new form DoanhThu
     */
    public DoanhThu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bntSearch = new javax.swing.JButton();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jButton2 = new javax.swing.JButton();
        pnlChart = new javax.swing.JPanel();
        bntBCTK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOANH THU");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bntSearch.setBackground(new java.awt.Color(204, 204, 204));
        bntSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntSearch.setForeground(new java.awt.Color(255, 0, 0));
        bntSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Tra cuu.png"))); // NOI18N
        bntSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSearchActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Biểu đồ");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pnlChart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biểu đồ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pnlChart.setLayout(new javax.swing.BoxLayout(pnlChart, javax.swing.BoxLayout.LINE_AXIS));

        bntBCTK.setText("TẠO BÁO CÁO THỐNG KÊ");
        bntBCTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBCTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(bntSearch)
                .addGap(204, 204, 204))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntBCTK)
                            .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(bntBCTK)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSearchActionPerformed
        try {
            DefaultTableModel tbn = new DefaultTableModel();
            Connection con = ConnectionUtils.getMyConnection();
            int number;
            Vector row;

            Vector header = new Vector();
            header.add("Mã cửa hàng");
            header.add("Doanh thu");
            tbn.setColumnIdentifiers(header);

            String ma_ch;
            String query = "SELECT MACH FROM CUAHANG";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            
            NumberFormat nf = NumberFormat.getInstance();
            Locale locale = new Locale("en", "EN");
            NumberFormat en = NumberFormat.getInstance(locale);
            String doanhthu;
            while (rs.next()) {
                ma_ch = rs.getString(1);
                Statement st = con.createStatement();
                CallableStatement stmt = con.prepareCall("{? = call func_doanhthu_ch ('"
                        + ma_ch + "', "
                        + jMonthChooser1.getMonth() + ", "
                        + jYearChooser1.getYear() + ")}");
                stmt.registerOutParameter(1, Types.FLOAT);
                stmt.execute();
                row = new Vector();
                row.add(ma_ch);
                doanhthu = en.format(stmt.getLong(1));
                row.add(doanhthu);
                tbn.addRow(row);
            }
            row = new Vector();
            row.add("---");
            row.add("---");
            tbn.addRow(row);
            
            row = new Vector();
            row.add("TỔNG");
            Statement st = con.createStatement();
            CallableStatement stmt = con.prepareCall("{? = call func_doanhthu_ht ("
                    + jMonthChooser1.getMonth() + ", "
                    + jYearChooser1.getYear() + ")}");
            stmt.registerOutParameter(1, Types.FLOAT);
            stmt.execute();
            doanhthu = en.format(stmt.getLong(1));
            row.add(doanhthu);
            tbn.addRow(row);
            jTable1.setModel(tbn);

        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }//GEN-LAST:event_bntSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        try {
            Connection con = ConnectionUtils.getMyConnection();
            
            String ma_ch;
            String query = "SELECT MACH FROM CUAHANG";
            Statement stat = con.createStatement();
            ResultSet rs = stat.executeQuery(query);
            while (rs.next()) {
                ma_ch = rs.getString(1);
                Statement st = con.createStatement();
                CallableStatement stmt = con.prepareCall("{? = call func_doanhthu_ch ('"
                        + ma_ch + "', "
                        + jMonthChooser1.getMonth() + ", "
                        + jYearChooser1.getYear() + ")}");
                stmt.registerOutParameter(1, Types.FLOAT);
                stmt.execute();
                
                dcd.setValue(stmt.getLong(1), "Doanh thu", ma_ch);
            }
            JFreeChart jchart = ChartFactory.createBarChart3D("DOANH THU HỆ THỐNG", "MÃ CỬA HÀNG", "VNĐ", dcd, PlotOrientation.VERTICAL, true, true, true);
            CategoryPlot plot = jchart.getCategoryPlot();
            plot.setRangeCrosshairPaint(Color.black);
            ChartFrame charFrm = new ChartFrame("DOANH THU", jchart, true);
            charFrm.setVisible(false);
            charFrm.setSize(500, 400);
            ChartPanel chartPanel = new ChartPanel(jchart);
            
            pnlChart.removeAll();
            pnlChart.add(chartPanel);
            pnlChart.updateUI();
            
        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bntBCTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBCTKActionPerformed
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document(PageSize.A4) {
        };
        try {

            PdfWriter.getInstance(doc, new FileOutputStream(path + "BCTK.pdf"));
            doc.open();
            doc.addCreationDate();
            doc.addTitle("BCTK");
            doc.addSubject("BCTK");
            
            Paragraph prgTieuDe = new Paragraph("BAO CAO THONG KE DOANH THU THANG " + jMonthChooser1.getMonth() + "/" + jYearChooser1.getYear());
            prgTieuDe.setAlignment(Element.ALIGN_CENTER);
            prgTieuDe.setSpacingBefore(20);
            prgTieuDe.setSpacingAfter(20);
            doc.add(prgTieuDe);
            
            PdfPTable tbl = new PdfPTable(2);

            tbl.addCell("Ma CH");
            tbl.addCell("Doanh thu");
            

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String mach = jTable1.getValueAt(i, 0).toString();
                String dthu = jTable1.getValueAt(i, 1).toString();
                
                tbl.addCell(mach);
                tbl.addCell(dthu);

            }
            doc.add(tbl);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DS_NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DS_NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }//GEN-LAST:event_bntBCTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoanhThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DoanhThu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBCTK;
    private javax.swing.JButton bntSearch;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JPanel pnlChart;
    // End of variables declaration//GEN-END:variables
}
