/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ConnectDB.ConnectionUtils;
import com.itextpdf.text.PageSize;
import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;
import java.text.NumberFormat;
import java.util.Locale;

import java.io.*;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author DOAN TU QUYNH
 */
public class DS_NhapKho extends javax.swing.JFrame {

    DefaultTableModel tbn = new DefaultTableModel();

    public DS_NhapKho() {
        initComponents();
        loadData();
    }

    public void loadData() {
        try {
            DefaultTableModel tbn = new DefaultTableModel();
            Connection con = ConnectionUtils.getMyConnection();
            int number;
            Vector row;

            CallableStatement stmt = con.prepareCall("{? = call func_ds_nhapkho}");
            stmt.registerOutParameter(1, OracleTypes.CURSOR);
            stmt.execute();
            ResultSet rs = (ResultSet) stmt.getObject(1);
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount(); //Tra ve so cot

            Vector header = new Vector();
            header.add("Mã sản phẩm");
            header.add("Tên sản phẩm");
            header.add("Đơn giá");
            header.add("Số lượng nhập");
            header.add("Thành tiền");
            tbn.setColumnIdentifiers(header);

            NumberFormat nf = NumberFormat.getInstance();
            Locale locale = new Locale("en", "EN");
            NumberFormat en = NumberFormat.getInstance(locale);

            long tong = 0;
            long thanhtien;
            while (rs.next()) {
                row = new Vector();
                for (int i = 1; i <= number; i++) {
                    row.addElement(rs.getString(i));
                }

                thanhtien = rs.getLong(3) * rs.getLong(4);
                String thanhtien1 = en.format(thanhtien);
                row.addElement(thanhtien1);
                tong += thanhtien;
                tbn.addRow(row);
            }
            row = new Vector();
            row.addElement("---");
            row.addElement("---");
            row.addElement("---");
            row.addElement("---");
            row.addElement("---");
            tbn.addRow(row);
            row = new Vector();
            row.addElement("");
            row.addElement("");
            row.addElement("");

            String tong1 = en.format(tong);
            row.addElement("TỔNG");
            row.addElement(tong1);
            tbn.addRow(row);
            jTable1.setModel(tbn);

        } catch (Exception ex) {
            System.out.print(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bntPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHẬP KHO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Backward (black).png"))); // NOI18N
        jButton1.setText("QUAY LẠI ");
        jButton1.setMaximumSize(new java.awt.Dimension(131, 38));
        jButton1.setMinimumSize(new java.awt.Dimension(131, 38));
        jButton1.setPreferredSize(new java.awt.Dimension(131, 38));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bntPrint.setBackground(new java.awt.Color(153, 204, 255));
        bntPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntPrint.setForeground(new java.awt.Color(51, 51, 255));
        bntPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Print.png"))); // NOI18N
        bntPrint.setText("IN");
        bntPrint.setMaximumSize(new java.awt.Dimension(131, 38));
        bntPrint.setMinimumSize(new java.awt.Dimension(131, 38));
        bntPrint.setPreferredSize(new java.awt.Dimension(131, 38));
        bntPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bntPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPrintActionPerformed
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document(PageSize.A4) {
        };
        try {

            PdfWriter.getInstance(doc, new FileOutputStream(path + "DS_NhapKho.pdf"));
            doc.open();
            doc.addCreationDate();
            doc.addTitle("Danh sach Nhap kho");
            doc.addSubject("Danh sach Nhap kho");
            
            Paragraph prgTieuDe = new Paragraph("DANH SACH NHAP KHO");
            prgTieuDe.setAlignment(Element.ALIGN_CENTER);
            prgTieuDe.setSpacingBefore(10);
            prgTieuDe.setSpacingAfter(10);
            doc.add(prgTieuDe);
            
            PdfPTable tbl = new PdfPTable(5);

            tbl.addCell("Ma SP");
            tbl.addCell("Ten SP");
            tbl.addCell("Don gia");
            tbl.addCell("SL Nhap");
            tbl.addCell("Thanh tien");

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String ma = jTable1.getValueAt(i, 0).toString();
                String ten = jTable1.getValueAt(i, 1).toString();
                String dgia = jTable1.getValueAt(i, 2).toString();
                String sl = jTable1.getValueAt(i, 3).toString();
                String ttien = jTable1.getValueAt(i, 4).toString();
                tbl.addCell(ma);
                tbl.addCell(ten);
                tbl.addCell(dgia);
                tbl.addCell(sl);
                tbl.addCell(ttien);

            }
            doc.add(tbl);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(DS_NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(DS_NhapKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
//        String filename = "DS_NhapKho";
//        try {
//            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("reports/"+filename+".pdf"));
//            document.open();
//            
//            //set attributes
//            document.addCreationDate();
//            document.addTitle("Danh sach Nhap kho");
//            document.addSubject("Danh sach Nhap kho");
//            
//            Paragraph prgTieuDe = new Paragraph("DANH SACH NHAP KHO", fontTieuDe1);
//            prgTieuDe.setAlignment(Element.ALIGN_CENTER);
//            prgTieuDe.setSpacingBefore(10);
//            prgTieuDe.setSpacingAfter(10);
//            document.add(prgTieuDe);
//            
//            document.close();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        //Mo file pdf sau khi dinh dang va write
//        try {
//            File file = new File("report/"+filename+".pdf");
//            if(!Desktop.isDesktopSupported()) {
//                System.out.print("Not supported!");
//                return;
//            }
//            Desktop destop = Desktop.getDesktop();
//            if(file.exists())
//                destop.open(file);
//        } catch (Exception e){
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_bntPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DS_NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DS_NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DS_NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DS_NhapKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DS_NhapKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPrint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
