CREATE TABLE CTHD (
    SOHD CHAR(4) NOT NULL,
    MASP CHAR(4) NOT NULL,
    SOLUONG INT,
    CONSTRAINT pk_cthd PRIMARY KEY (SOHD, MASP)
);
---------------------------------------------------
ALTER TABLE CTHD ADD CONSTRAINT fk_cthd_hd FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD);
ALTER TABLE CTHD ADD CONSTRAINT fk_cthd_sp FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP);
---------------------------------------------------
--CTHD
INSERT INTO CTHD VALUES('HD01','XD01',1);
INSERT INTO CTHD VALUES('HD01','BH03',1);
INSERT INTO CTHD VALUES('HD02','DE01',1);
INSERT INTO CTHD VALUES('HD02','RU04',2);
INSERT INTO CTHD VALUES('HD03','XD07',1);
INSERT INTO CTHD VALUES('HD03','BH02',1);
INSERT INTO CTHD VALUES('HD03','GT02',1);
INSERT INTO CTHD VALUES('HD03','SE02',1);
INSERT INTO CTHD VALUES('HD04','XD12',1);
INSERT INTO CTHD VALUES('HD05','BR01',5);
INSERT INTO CTHD VALUES('HD06','MK02',3);
INSERT INTO CTHD VALUES('HD06','GT03',1);
INSERT INTO CTHD VALUES('HD07','B001',2);
INSERT INTO CTHD VALUES('HD08','XD03',1);
INSERT INTO CTHD VALUES('HD08','XD10',1);
INSERT INTO CTHD VALUES('HD09','BH01',1);
INSERT INTO CTHD VALUES('HD09','DE01',2);
INSERT INTO CTHD VALUES('HD10','DE02',3);
INSERT INTO CTHD VALUES('HD11','SE03',2);
INSERT INTO CTHD VALUES('HD12','BR01',5);
INSERT INTO CTHD VALUES('HD12','XD08',1);
INSERT INTO CTHD VALUES('HD13','XD11',1);
INSERT INTO CTHD VALUES('HD13','MK01',1);
INSERT INTO CTHD VALUES('HD14','XD06',1);
INSERT INTO CTHD VALUES('HD15','XD08',2);
INSERT INTO CTHD VALUES('HD16','RU03',4);
INSERT INTO CTHD VALUES('HD17','XD01',3);
INSERT INTO CTHD VALUES('HD18','GT01',1);
INSERT INTO CTHD VALUES('HD18','MK02',1);
INSERT INTO CTHD VALUES('HD19','XD09',1);
INSERT INTO CTHD VALUES('HD20','XD09',1);
INSERT INTO CTHD VALUES('HD20','RU02',2);

